### ISSUE TITLE
More descriptive run time errors?

### ISSUE THREAD

**Issue by kannon92** [jturney/ambit#10]
Would it be possible to have more detailed run-time errors printing?  

Right now, I get this:  RuntimeError: Invalid AC (Left) index size

I know this means that I messed up allocating the tensor, but would it be possible to print the tensor name/dimensions?

**Comment by jturney** [comment]
Should be simple to do. The data you're interested in should be available at that place in the code.

**Comment by jturney** [comment]
I committed code the other day for this. Re-open if not descriptive enough.
