### ISSUE TITLE
Compiler error on SUSE LINUX

### ISSUE THREAD

**Issue by kannon92** [jturney/ambit#11]
I am not able to compile ambit on our SUSE LINUX box.  

    /home/kannon/src/ambit/src/tensor/indices.cc: In function ‘std::string ambit::indices::to_string(const      Indices&, const string&)’:
    /home/kannon/src/ambit/src/tensor/indices.cc:164:15: error: ‘ostream_iterator’ is not a member of ‘std’
               std::ostream_iterator<string>(ss, sep.c_str()));
               ^
    /home/kannon/src/ambit/src/tensor/indices.cc:164:43: error: expected primary-expression before ‘>’ token
               std::ostream_iterator<string>(ss, sep.c_str()));
                                           ^
I am able to fix this error by including iterator in indices.cc.  

I get another error in timer.cc.  

    /home/kannon/src/ambit/src/tensor/timer.cc: In function ‘void ambit::timer::  {anonymous}::print_timer_info(ambit::timer::{anonymous}::TimerDetail*)’:
    /home/kannon/src/ambit/src/tensor/timer.cc:91:20: error: ‘strlen’ is not a member of ‘std’
               60 - strlen(buffer), "", timer->name.c_str());
                    ^
    make[2]: *** [src/CMakeFiles/ambit.dir/tensor/timer.cc.o] Error 1
    make[1]: *** [src/CMakeFiles/ambit.dir/all] Error 2
    make: *** [all] Error 2

I included string.h in timer.cc.  This seems to allow the code to compile.

**Comment by jturney** [comment]
Thanks, I've patched my local version. I'll get it checked in today hopefully.

**Comment by kannon92** [comment]
Thank you.
