### ISSUE TITLE
psi4 interface testing

### ISSUE THREAD

**Issue by loriab** [jturney/ambit#18]
Test case(s) in psi4 that make use of ambit would be helpful to judge whether the interface is working. Similarly, right now the ambit plugin lacks any ambit dependence, so it'd be nice to clear that up.

**Comment by loriab** [comment]
Also, I get the below

```
/Users/loriab/linux/psi4conda7/lib/python2.7/site-packages/ambit/__init__.py:2: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  from .pyambit import TensorType, EigenvalueOrder
```

even from a simple file run from psi4:

```
if True:
    import ambit

    aA = ambit.Tensor(ambit.TensorType.CoreTensor, "A", [2, 2])
    aB = ambit.Tensor(ambit.TensorType.CoreTensor, "B", [2, 2])
    aC = ambit.Tensor(ambit.TensorType.CoreTensor, "C", [2, 2])

    nA = np.asarray(aA)
    nA.flat[:] = 3.0
    nA = nA.copy()

    nB = np.asarray(aB)
    nB.flat[:] = 4.0
    nB = nB.copy()

    nC = np.asarray(aC)
    nC.flat[:] = 0.0
    nC = nC.copy()

    # dot product
    aC["ik"] = aA["ij"] * aB["jk"]
    nC = np.dot(nA, nB)

    compare_integers(1, int(np.allclose(aC, nC)), "Psi4 + Ambit library")  #TEST

    clean()
```

**Comment by loriab** [comment]
Huh, you're right about the psi4 plugin actually using ambit. I had checked one out and found no traces of it, so perhaps I misspelled something in the checkout. Sorry about that.

**Comment by loriab** [comment]
I'm done fiddling with the ambit build for now. So when you're satisfied with any resolution to the python problem above, please shift or mint a tag so psi4 cmake, psi4 conda, and ambit can stay in sync. Thanks!

**Comment by jturney** [comment]
I'm actually not able to compile right now, but if you have a chance can you try removing these [lines](https://github.com/jturney/ambit/blob/master/src/python/bindings.cc#L123-124)?

**Comment by loriab** [comment]
Helps but hurts, too. Looks like registration w/i Psi4 is an issue.

**Before removing those lines**
* ambit ctest passes
* test_operators.py passes
* that input above in this issue (here named ambittest.in) passes but with a registration error

```
>>> python "$(dirname $(which python ))"/../lib/python2.7/site-packages/ambit/tests/test_operators.py
.......x.................x..xx.......
----------------------------------------------------------------------
Ran 37 tests in 0.549s

OK (expected failures=4)
```
```
>>> psi4 ambittest.in 
/shortened/lib/python2.7/site-packages/ambit/__init__.py:2: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  from .pyambit import TensorType, EigenvalueOrder
	Psi4 + Ambit library..............................................PASSED
```

**After removing those lines**
* ambit ctest passes
* test_operators.py fails
* that input above in this issue (here named ambittest.in) passes _without_ a registration error

```
>>> python "$(dirname $(which python ))"/../lib/python2.7/site-packages/ambit/tests/test_operators.py
EEEEEEExEEEEEEEEEEEEEEEEExEExxEEEEEEE
======================================================================
ERROR: test_Cij_divide_equal_2 (__main__.TestOperatorOverloading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/loriab/linux/psi4conda7/bin/../lib/python2.7/site-packages/ambit/tests/test_operators.py", line 182, in test_Cij_divide_equal_2
    [aC, nC] = self.build_and_fill2("C", [ni, nj])
  File "/Users/loriab/linux/psi4conda7/bin/../lib/python2.7/site-packages/ambit/tests/test_operators.py", line 17, in build_and_fill2
    data = T.tensor.data()
TypeError: No Python class registered for C++ class std::vector<double, std::allocator<double> >
...
Ran 37 tests in 0.013s

FAILED (errors=33, expected failures=4)
```
```
>>> psi4 ambittest.in 
	Psi4 + Ambit library..............................................PASSED
```

**Comment by loriab** [comment]
Everyone is itching to evict Boost from Psi4 in favor of pybind11. Perhaps Ambit can switch at the same time, and we'll just live with the registration warning in the meantime.

**Comment by jturney** [comment]
This sounds vaguely familiar to me on why I had left both vector registrations in. We'll live with the warning for now like you suggest. I'll plan to visit soon and help work on the pybind11 conversion.

**Comment by loriab** [comment]
Ok, sounds good. If you're online, could you do a version bump, so psi4 is grabbing something more concrete than a commit hash?

**Comment by jturney** [comment]
Done: ```v0.2```

**Comment by loriab** [comment]
Thanks, done: https://github.com/psi4/psi4/commit/caa78257e2fa7a0c5cbde66d0e33758ff03d1787
