### ISSUE TITLE
Python testing suite

### ISSUE THREAD

**Issue by jturney** [jturney/ambit#3]
The C++ testing is good at validating the results obtained by the tensor code. Our Python code is only manually verified.

**Comment by jturney** [comment]
This is well on its way.  tests/test_operators.cc is now duplicated in lib/test_operators.py and the beginnings of test_blocks.cc is found in test_blocks.py.  The tests are using Python 3 features at this time. Need to test the operator overloading code for Python 2 compatibility.

**Comment by jturney** [comment]
Current tests pass in Python 2 and 3.

**Comment by robparrish** [comment]
Nice work Jet!

-Rob
